# Week 4 part 1 - NumPy

In this notebook you will learn about one of the most widely used mathematical Python modules: NumPy.  You can read more about NumPy [on their homepage](https://numpy.org/).

NumPy is a Python module which has functions for working with vectors and matrices (and higher-dimensional arrays) and for working with random numbers.  [Here is a link to the documentation](https://numpy.org/doc/stable/).

Of course, if we wanted we could represent matrices and vectors using lists in plain Python and write functions to do matrix multiplication, vector addition, and so on. The advantage of NumPy  is that all this code has been written and tested for us by experts in numerical linear algebra.  The big number of high-quality, popular, and freely available modules for mathematical computing is one reason you're learning Python instead of another computer language.

You often see NumPy imported using `import numpy as np`.  As you saw in the previous notebook this just saves a bit of typing: after doing this you can use `np.functionName` instead of `numpy.functionName`.

## NumPy arrays

The most important object NumPy provides is the `array`.  These are rectangular grids of numbers which you can use to represent matrices and vectors.  The easiest way to create arrays is by using `np.array()` with the argument being a list of the rows of the matrix or vector you want to create, each row being a list of its entries.

In [1]:
import numpy as np
v = np.array([[1, 2]])         # 1x2 row vector - a list containing one row, [1, 2]
w = np.array([[1], [2]])       # 2x1 column vector - a list of two rows, [1] and [2]
A = np.array([[1, 2],[3, 4]])  # 2x2 matrix - a list containing two rows, [1,2] and [3,4]

print(v, " is a 1x2 row vector\n")
print(w, " is a 2x1 column vector \n")
print(A, " is a 2x2 matrix")

[[1 2]]  is a 1x2 row vector

[[1]
 [2]]  is a 2x1 column vector 

[[1 2]
 [3 4]]  is a 2x2 matrix


You can get the shape of an array `a` with `a.shape`

In [2]:
print(v.shape)  # v is a row vector, so it is 1x2
print(w.shape)  # w is a 2x1 column vector
print(A.shape)  # A is a 2x2 matrix

(1, 2)
(2, 1)
(2, 2)


and you can transpose an array with the `.transpose()` method

In [3]:
A.transpose()

array([[1, 3],
       [2, 4]])

`A.transpose()` returns a new array which is the transpose of `A`. It doesn't modify `A` itself, as you can see by running the next cell:

In [4]:
A

array([[1, 2],
       [3, 4]])

The `np.linspace` function will be very useful later when we want to plot graphs of functions.  To create a one-dimensional array of `n` equally spaced points starting at `a` and ending at `b`, use `np.linspace(a, b, n)`:

In [5]:
np.linspace(0, 1, 11) # 11 equally spaced points starting at 0, ending at 1

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [6]:
np.linspace(1, 3, 9) # 9 equally spaced points starting at 1, ending at 3

array([1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 , 2.75, 3.  ])

You can use a for loop to do something for each element of a 1-dimensional array in turn:

## Accessing array elements

To access the entries of an array you can use the square-bracket index notation just like for lists, remembering that Python uses indices starting at 0, not 1.  If `A` is a two-dimensional array then either `A[i, j]` or `A[i][j]` can be used to get the entry in row `i`, column `j`.

What will the following commands print?

In [7]:
A[1][1]

4

In [8]:
A[0, 1]

2

In [9]:
A[1][0]

3

You have to be careful when accessing elements of row and column vectors defined as $1\times n$ and $n\times 1$ numpy arrays.  Since numpy sees these as two-dimensional arrays, you have to use two pairs of square brackets:
 - the $j$th element of the row vector `v` is `v[0][j]` or `v[0, j]`
 - the $i$th element of the column vector `w` is `w[i][0]` or `w[i, 0]`

In [10]:
v = np.array([[1,2,3]]) # 1x3 row vector
w = np.array([[1], [2], [3]]) # 3x1 column vector
print(v[0][1]) # entry in column 1 of the row vector v
print(w[1, 0]) # entry on row 1 of the column vector w

2
2


NumPy distinguishes between one-dimensional arrays, which have shape `(n,)` (a size-one tuple with `n` elements), and two-dimensional arrays with shape `(1,n)`, even though these are both essentially lists of `n` numbers.  This can be confusing - be careful!

In [11]:
v1 = np.array([1,2,3])    # a 1-D array with length 3
v2 = np.array([[1,2,3]])  # a 2-D array with shape (1,3)
print("v1 has shape", v1.shape, "and v2 has shape", v2.shape)

v1 has shape (3,) and v2 has shape (1, 3)


You can extract rows or columns from a 2-dimensional array with a kind of slice notation similar to that we used for lists and strings. Here's how to get rows:

In [12]:
A = np.array([[1, 2], [3, 4]])
print(A[1, :]) # row 1 of A, as a 1 dimensional array - the : is shorthand for "all entries"

[3 4]


In [13]:
A[:, 0] # column 0 of A, as a 1D array

array([1, 3])

If you need to reshape these into 2D arrays you can use `np.reshape` - for example:

In [0]:
A[:, 0].reshape(2,1) # the 0th column as a 2x1 column vector

In [0]:
A[0, :].reshape(1, 2) # the 0th row as a 1x2 row vector

## Equality of arrays

You **cannot** use `==` to check if two NumPy arrays are equal! NumPy overrides the `==` operator so that if `v` and `w` are arrays, `v == w` is an array with `True` in the positions where `v` and `w` are equal and `False` in the positions where they are different.

In [0]:
v = np.array([[1, 2, 3]])
w = np.array([[3, 2, 1]])
v == w

If you want to check if two arrays are equal you need to use `np.array_equal(x, y)`, which is `True` if and only if `x` and `y` are arrays with the same shape and the same entries.

In [0]:
np.array_equal(v, w)

In [0]:
np.array_equal(v, v)

## Unassessed exercises

### Exercise 1 - creating arrays

It's very important to remember that the input of the `np.array` function must be a list whose elements are lists which represent the rows of the matrix or vector you're trying to create.  In particular, if you want to create a row vector the argument of `np.array` should be a list containing another list whose elements are the entries of your row vector.

**Create the vectors $\mathbf{x} = \begin{pmatrix} 0 \\ 0 \\ 1 \end{pmatrix}, \mathbf{y} = \begin{pmatrix}3&2&1\end{pmatrix}$ and the matrix $B = \begin{pmatrix} 1 & 2 & 3 \\ 3 & 2 & 1 \\ 1 & 2 & 3 \end{pmatrix}$ as numpy arrays.**

In [1]:
import numpy as np
x = np.array([[0], [0], [1]])
y = np.array([[3, 2, 1]])
B = np.array([[1, 2, 3], [3, 2, 1], [1, 2, 3]])

**Check their shapes.**

In [2]:
x.shape # should be (3, 1)

(3, 1)

In [3]:
y.shape # should be (1, 3)

(1, 3)

In [4]:
B.shape # should be (3, 3)

(3, 3)

## Exercise 2 - write your own dot product

Write a function that returns the dot product of two $n\times 1$ NumPy arrays. Your function should work for any $n$ - but if you are unsure how to start, try making a function that works only for $n=2$.

The dot product of $\begin{pmatrix} x_1\\x_2\end{pmatrix}$ and $\begin{pmatrix} y_1\\ y_2\end{pmatrix}$ is defined to be the number $x_1y_1+x_2y_2$, and it is defined similarly for larger vectors.

In [9]:
def dotproduct(x, y):
    """
    input: numpy arrays x and y, both with shape (n, 1) for some n
    output: the dot product of x and y
    """
    dp = 0
    for i in range(x.shape[0]):
        dp = dp + x[i][0] * y[i][0]
    return dp
    # when you've learned about NumPy matrix multiplication you can do
    # return np.matmul(x, y.transpose())[0, 0]

x = np.array([[1],[2],[3]])
y = np.array([[3],[2],[1]])
print(x.shape, y.shape)
dotproduct(x,y)

(3, 1) (3, 1)


10

## Exercise 3 - sum of array entries

If you want to write a for loop that where the index variable takes every value in a NumPy array `A` in turn, `for x in A:` won't work if the array is 2-dimensional (remember that our row and column vectors are 2-dimensional). Instead you can use `for x in np.nditer(A):` which will make `x` have the value of each of the entries of `A` in turn.

**Write a function that returns the sum of the entries of a numpy array of any shape.**

In [12]:
def arraysum(A):
    """
    input:  a numpy array A of any shape
    output: the sum of the entries of A
    """
    total = 0
    for x in np.nditer(A):
        total = total + x
    return total

# you could also just use np.sum(A)

Here are some test cases for your function.

In [13]:
print(arraysum(np.array([1,2,3]))) # should be 6
print(arraysum(np.array([[1,2,3]]))) # should be 6
print(arraysum(np.array([[1],[2],[3]]))) # should be 6
print(arraysum(np.array([[1,2],[3,4]]))) # should be 10

6
6
6
10
